swagger: "2.0"
info:
  version: "1.0.0"
  title: go_gateway_new
  description: The API for the miniblog project
  contact:
    name: luomiaozhong
    email: 2383304714@qq.com
    url: https://github.com/miao-crispy-corner/go_gateway_new.git
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths:



